code: "Probability of Environment Risk"
nameId: "Probability of Environment Risk"
descriptionId: ""
type: "Number"
isCloneable: true
numberDecimals: 2
isCurrencyValue: false
maximumNumber: 100
listItems: []
